project:
  name: Aerospike-DBaaS
  owner: quickstart-eng@amazon.com
  package_lambda: true
  shorten_stack_name: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  regions:
  - us-east-1
  template: templates/aerospike-cluster-entrypoint-new-vpc.template.yaml
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    NumberOfAZs: 2
    AccessCIDR: 0.0.0.0/0
    KeyPairName: default
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-aerospike/
tests:
  aerospike-single-region:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
    regions:
    - us-east-1

